#version 450
layout(local_size_x = 32, local_size_y = 1) in;

layout(set = 0, binding = 0) buffer lay0 { int inbuf[]; };
layout(set = 0, binding = 1) buffer lay1 { int outbuf[]; };

void main() {
	// drop threads outside the buffer dimensions.
	if(32u <= gl_GlobalInvocationID.x || 1u <= gl_GlobalInvocationID.y){
		return;	
	}
	const uint id = gl_GlobalInvocationID.x; // current offset

	outbuf[id] = inbuf[id] * inbuf[id];
}
